@extends('L.blank_page_F')

@section('PageTitle')
MS-Flex ,Dynamic Website Solution,Web software development in India
@endsection

@section('PageDescription')
MS-Flex a complate website solution is that can fullfill all requirements for a professional website for company, school,education Institute, gov organizations.
@endsection


@section('PageKeywords')
professional website solution india,professional website,website for company,website for school,website for education institute,website for government,dynamic solution
@endsection

@section('PageLocation')
<li class="active">Products</li>
<li class="active">MS-Flex</li>
@endsection

@section('PageHeading')
<img alt="Top Dynamic Solution provider in India " src="{{asset('images/master/Ms_Flex.png')}}"><br> <small>A Complate Website Solution</small>
@endsection

@section('PageContent')
<p class="padding-top-20">MS-Flex is developed by Millions Solutions LLP for industry who want to became online in very <b class="ms-seo-b">professional</b> and <b class="ms-seo-b">dynamic</b> way to expand your business in <i>India & around the globe</i> .</p>
<p class="padding-top-20">MS-Flex a complete <b class="ms-seo-b">website solution</b> is build with modules that can fullfill all requirements for a <i><b class="ms-seo-b">professional website solution</b> for industry</i>, company, school/education Institute, government organizations/association, etc</i>.</p>
<p class="padding-top-20">Now days , Every one providing website development and web hosting services but we providing industry’s best fully customizable web application that can assure best service & performance with high security and with our only in our cloud policy that can secure client’s data securely and provide extra redundant solution to the client.</p>
<div  class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<h4 class="padding-top-20">MS-Flex Solution Includes</h4>
						<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
							<div class="single_pricing_text wow fadeIn" data-wow-duration="1s" style="visibility: hidden; animation-duration: 1s; animation-name: none;">
								<div class="pricing_head_text">
									<h5><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Custom Desiged Pages</h5>

								</div>

							</div>
						</div>

						<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
							<div class="single_pricing_text wow fadeIn" data-wow-duration="1s" style="visibility: hidden; animation-duration: 1s; animation-name: none;">
								<div class="pricing_head_text">
									<h5><i class="fa fa-server" aria-hidden="true"></i> Cloud Server</h5>

								</div>

							</div>
						</div>

						<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
							<div class="single_pricing_text wow fadeIn" data-wow-duration="1s" style="visibility: hidden; animation-duration: 1s; animation-name: none;">
								<div class="pricing_head_text">
									<h5><i class="fa fa-bookmark" aria-hidden="true"></i> Domain Name</h5>

								</div>

							</div>
						</div>

						<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
							<div class="single_pricing_text wow fadeIn" data-wow-duration="1s" style="visibility: hidden; animation-duration: 1s; animation-name: none;">
								<div class="pricing_head_text">
									<h5><i class="fa fa-codepen" aria-hidden="true"></i> MS-Flex Cloud Application</h5>


								</div>

							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="single_pricing_text wow fadeIn" data-wow-duration="1s" style="visibility: hidden; animation-duration: 1s; animation-name: none;">
								<div class="pricing_head_text">
									<h5><i class="fa fa-free-code-camp" aria-hidden="true"></i> Free 1 year Annual Maitance Contract</h5>


								</div>

							</div>
						</div>
</div>

						<div  class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<h4 class="padding-top-20">MS-Flex Cloud Application</h4>

							<p class="padding-top-20">MS-Flex Cloud Application developed on PHP platform with HTML5,CSS3,Javascript etc.</p>
							<p class="padding-top-20">This application includes Flex-Box Module with some other common modules like news management,events management,announcements management,documents management.</p>
							<p class="padding-top-20">Flex Box are main attraction of MS-Flex Cloud Application.Flex-Box are customized developed database driven modules that can place any where on website and display dynamic data on website.it can be any thing like graph of activity or image/graph rich report that can generated by MS-Flex Cloud application in real time.</p>
							<p class="padding-top-20">MS-Flex has also included custom designed <b class="ms-seo-b">dynamic solution</b> that can give a perfect and custom <i>dynamic solution</i> for every unique client as per their requirements.</p>
							<p class="padding-top-20">MS-Flex a complete <b class="ms-seo-b">website solution</b> is a combination of dynamic & static content website for any industry, company, school,education Institute, government organizations,association, etc.</p>
						</div>

<div class="hidden">
<h1>Professional Website Solution in India</h1>
<h2>Dynamic Solution</h2>
<a href="{{url('product/ms-flex')}}" alt="professional website solution in india ">Website for Company</a>
</div>

@endsection

@push('PageSidebar')
<div class="panel-footer ms-bg">
<span class="ms-text"><span class="lnr fa fa-info-circle ms-padding-right-10"></span>Our Website Solutions</span>

</div>
<div class="panel-body">
<ul>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Company Website</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> School Website</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Website for E-commerce</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Website for Government</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Website Solution</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Cloud based Website</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Database Driven Website</a></li>
									<li><a href="#"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Dynamic Website</a></li>


								</ul>
</div>


<div class="panel-footer ms-bg">
<span class="ms-text"><span class="lnr fa fa-industry ms-padding-right-10"></span>Our Services Avalaible in</span>

</div>
<div class="panel-body">
<ul>
									<li><a href=""><i class="fa fa-hand-o-right" aria-hidden="true"></i>All over India</a></li>




								</ul>
</div>
@endpush
